import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar";
import Image from "next/image";
import bg from "@/assets/bg.webp"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
        <Image src={bg} alt="background" width={1980} height={1080} className="fixed w-full h-screen object-cover opacity-50" />
      </body>
    </html>
  );
}
